SELECT [postcode]
      ,[suburb]
      ,[city]
      ,[state]
      ,[state_code]
      ,[lat]
      ,[lon]
      ,[district]
      ,[AUS_Area]
  FROM [2024-APR-IC-DW].[dbo].[AUS_Property]
